### ISSUE TITLE
Add support for the ability to disable certain model vendors

### ISSUE THREAD

**Issue by pillzu** [Aaronik/GPTModels.nvim#1]
As much as I appreciate being able to switch model, I'd like to disable certain ones, like `openai`, so that I don't have to go back to them over an over.

Maybe a config option like `vendors` would be a good idea to allow users to customize their experience (default being both ollama and openai)

**Comment by aaronik** [comment]
Yeah I think I see your point - especially if you have a lot of models, scrolling through them can be a bit tedious.

I just added a feature to help that, ctrl-p, which opens a telescope pop-up into which you can type your model. Would you mind trying that and letting me know if it satisfies your need?

**Comment by pillzu** [comment]
Hey Aaronik
First and foremost, loving the plugin ❤️ Thanks for adding this here (if I may, you should get a more streamlined way for people to contribute going forward... this is for sure gonna blow up XD)

That said, I did try the telescope tooling! As much as I like it, I honestly prefer to only have ollama as my main model right now. Maybe we can have a way to unbind some of the default keybindings?

**Comment by aaronik** [comment]
Well thank you, I appreciate your words! Just thinkin out loud here - what if it didn't show the openai models if the environment variable OPENAI_API_KEY isn't set? I could definitely see that being a feature. It probably should be like that already, actually. I'll add it to the TODO. Does that accomplish something like what you're lookin for?

**Comment by pillzu** [comment]
That'll honestly be awesome! I think it would totally achieve what i'd like to do. If I get time, I'll maybe give it a shot myself :)

**Comment by aaronik** [comment]
That's great! In that case I'm going to leave it open for you. The way to contribute is by forking, modifying, then syncing, making a PR. If you haven't done it before it's a bit bewildering the first time, but you'd figure it out.

If you don't mind, a few requests:
- [ ] Develop it test first. Tests ensure stability. All functionality should be tested before merging. It also forces you to get to know the code a little bit better, which leads to better code.
- [ ] Add another feature, whereby there's a message to the user indicating that this hiding of the openai models is taking place. Also write this test first if possible :)

I'm happy to help out, too. Feel free to reach out for any guidance along the way, about technicals or style or whatever. Also happy to pair for an hour on it!

**Comment by pillzu** [comment]
Hey Aaronik
Thanks a lot for helping me get started. I've made some changes but am running into trivial errors that I am not sure on how to resolve (I've added TODO/FIX notes to the code itself so you should be able to see them right away; otherwise if you run tests, they'd be there as well :sweat: )

Do you think you could help out a little bit with the design on this one? I haven't work a lot with lua before so kinda confused on how to go forward :confused:

**Comment by brunobmello25** [comment]
is this fixed with #2? if so I believe we can close this issue :D

**Comment by aaronik** [comment]
> is this fixed with #2? if so I believe we can close this issue :D

It's not but fear not! I'm part way through implementing this along with showing all the available OpenAI models 🙂

@pillzu it's taken forever and didn't go how I originally was hoping but nonetheless it's almost here 😄

**Comment by aaronik** [comment]
Also fyi the forever taking is not because of the complexity of the change, rather other things I prioritized in the plugin and in life.

But the mornings and evenings are starting to cool down again and computer projects are starting to feel more appealing again!

**Comment by brunobmello25** [comment]
hehe that's great to hear! let me know if there's anything I can do to help 😊

**Comment by aaronik** [comment]
@pillzu and @brunobmello25 great news, this has finally landed! @pillzu thanks for your infinite patience on this one. It turns out there was sooooo much left to do before implementing this in the best way, which involved showing users all available openai chat models, be it many or none. There was lots to do to get here but the plugin is a lot more usable for people who want to use it only with ollama _or_ only with openai. Fixed at least one really nasty bug on the way as well.

@pillzu Can you let me know if you're satisfied with the experience introduced here?

**Comment by brunobmello25** [comment]
Just tested it here, working perfectly!

**Comment by aaronik** [comment]
Gonna close this as I think it's completed. @pillzu Please feel free to reopen or comment and I'll reopen if your needs here haven't been met. Thanks again for all your patience with this!
